export const greenWin: (string|null)[][][] = [
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ],
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            "red"
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ],
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            "red"
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ],
    [
        [
            "green",
            "green",
            "green",
            "green"
        ],
        [
            null,
            null,
            null,
            "red"
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ]
]

export const redWinner: (string|null)[][][] = [
        [
            [
                null,
                null,
                null,
                null
            ],
            [
                null,
                null,
                null,
                null
            ],
            [
                null,
                null,
                null,
                null
            ],
            [
                null,
                null,
                null,
                null
            ]
        ],
        [
            [
                null,
                null,
                null,
                null
            ],
            [
                null,
                null,
                null,
                null
            ],
            [
                null,
                null,
                null,
                null
            ],
            [
                null,
                null,
                null,
                null
            ]
        ],
        [
            [
                null,
                null,
                null,
                "green"
            ],
            [
                null,
                null,
                null,
                "green"
            ],
            [
                null,
                null,
                null,
                null
            ],
            [
                null,
                null,
                null,
                null
            ]
        ],
        [
            [
                null,
                null,
                "green",
                "red"
            ],
            [
                null,
                null,
                "green",
                "red"
            ],
            [
                null,
                null,
                null,
                "red"
            ],
            [
                null,
                null,
                null,
                "red"
            ]
        ]
]

export const noWinner: (string|null)[][][] = [
    [
        [
            "red",
            null,
            null,
            null
        ],
        [
            null,
            null,
            "green",
            "red"
        ],
        [
            "green",
            null,
            "red",
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ],
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            "red",
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            "green",
            null
        ]
    ],
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            "red",
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            "green"
        ],
        [
            null,
            "red",
            null,
            null
        ]
    ],
    [
        [
            "green",
            null,
            null,
            "green"
        ],
        [
            null,
            "red",
            null,
            null
        ],
        [
            "green",
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ]
]