export const cube: (null|string)[][][] = [
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ],
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ],
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ],
    [
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null
        ]
    ]
]